export const UPDATE_VEHICLE_SIGN_UP_PROPS = 'UPDATE_VEHICLE_SIGN_UP_PROPS';
export const ATTEMPT_VEHICLE_SIGN_UP = 'ATTEMPT_VEHICLE_SIGN_UP';
export const VEHICLE_SIGN_UP_SUCCESS = 'VEHICLE_SIGN_UP_SUCCESS';
export const VEHICLE_SIGN_UP_FAILED = 'VEHICLE_SIGN_UP_FAILED';
export const RESET_VEHICLE_SIGNUP = 'RESET_VEHICLE_SIGNUP';

export const UPDATE_CUSTOMER_SIGN_UP_PROPS = 'UPDATE_CUSTOMER_SIGN_UP_PROPS';
export const ATTEMPT_CUSTOMER_SIGN_UP = 'ATTEMPT_CUSTOMER_SIGN_UP';
export const CUSTOMER_SIGN_UP_SUCCESS = 'CUSTOMER_SIGN_UP_SUCCESS';
export const CUSTOMER_SIGN_UP_FAILED = 'CUSTOMER_SIGN_UP_FAILED';
export const RESET_CUSTOMER_SIGNUP = 'RESET_CUSTOMER_SIGNUP';

export const UPDATE_CUSTOMER_UPDATE_PROPS = 'UPDATE_CUSTOMER_UPDATE_PROPS';
export const ATTEMPT_CUSTOMER_UPDATE = 'ATTEMPT_CUSTOMER_UPDATE';
export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS';
export const CUSTOMER_UPDATE_FAILED = 'CUSTOMER_UPDATE_FAILED';
export const RESET_CUSTOMER_UPDATE = 'RESET_CUSTOMER_UPDATE';

export const UPDATE_CUSTOMER_DELETE_PROPS = 'UPDATE_CUSTOMER_DELETE_PROPS';
export const ATTEMPT_CUSTOMER_DELETE = 'ATTEMPT_CUSTOMER_DELETE';
export const CUSTOMER_DELETE_SUCCESS = 'CUSTOMER_DELETE_SUCCESS';
export const CUSTOMER_DELETE_FAILED = 'CUSTOMER_DELETE_FAILED';
export const RESET_CUSTOMER_DELETE = 'RESET_CUSTOMER_DELETE';

export const UPDATE_CUSTOMER_SIGN_IN_PROPS = 'UPDATE_CUSTOMER_SIGN_IN_PROPS';
export const ATTEMPT_CUSTOMER_SIGN_IN = 'ATTEMPT_CUSTOMER_SIGN_IN';
export const CUSTOMER_SIGN_IN_SUCCESS = 'CUSTOMER_SIGN_IN_SUCCESS';
export const CUSTOMER_SIGN_IN_FAILED = 'CUSTOMER_SIGN_IN_FAILED';
export const RESET_CUSTOMER_SIGN_IN = 'RESET_CUSTOMER_SIGN_IN';

export const UPDATE_CREATE_VEHICLE_PROPS = 'UPDATE_CREATE_VEHICLE_PROPS';
export const ATTEMPT_CREATE_VEHICLE = 'ATTEMPT_CREATE_VEHICLE';
export const CREATE_VEHICLE_SUCCESS = 'CREATE_VEHICLE_SUCCESS';
export const CREATE_VEHICLE_FAILED = 'CREATE_VEHICLE_FAILED';
export const RESET_CREATE_VEHICLE = 'RESET_CREATE_VEHICLE';

export const UPDATE_UPDATE_VEHICLE_PROPS = 'UPDATE_UPDATE_VEHICLE_PROPS';
export const ATTEMPT_UPDATE_VEHICLE = 'ATTEMPT_UPDATE_VEHICLE';
export const UPDATE_VEHICLE_SUCCESS = 'UPDATE_VEHICLE_SUCCESS';
export const UPDATE_VEHICLE_FAILED = 'UPDATE_VEHICLE_FAILED';
export const RESET_UPDATE_VEHICLE = 'RESET_UPDATE_VEHICLE';

export const ATTEMPT_LIST_VEHICLE = 'ATTEMPT_LIST_VEHICLE';
export const LIST_VEHICLE_SUCCESS = 'LIST_VEHICLE_SUCCESS';
export const LIST_VEHICLE_FAILED = 'LIST_VEHICLE_FAILED';
export const RESET_LIST_VEHICLE = 'RESET_LIST_VEHICLE';

export const UPDATE_VEHICLE_O_UPDATE_PROPS = 'UPDATE_VEHICLE_O_UPDATE_PROPS';
export const ATTEMPT_VEHICLE_O_UPDATE = 'ATTEMPT_VEHICLE_O_UPDATE';
export const VEHICLE_O_UPDATE_SUCCESS = 'VEHICLE_O_UPDATE_SUCCESS';
export const VEHICLE_O_UPDATE_FAILED = 'VEHICLE_O_UPDATE_FAILED';
export const RESET_VEHICLE_O_UPDATE = 'RESET_VEHICLE_O_UPDATE';

export const DELETE_DRIVER = 'DELETE_DRIVER';

export const LOGIN_VEHICLE_O_UPDATE_PROPS = 'LOGIN_VEHICLE_O_UPDATE_PROPS';
export const ATTEMPT_VEHICLE_O_LOGIN = 'ATTEMPT_VEHICLE_O_LOGIN';
export const VEHICLE_O_LOGIN_SUCCESS = 'VEHICLE_O_UPDATE_SUCCESS';
export const VEHICLE_O_LOGIN_FAILED = 'VEHICLE_O_LOGIN_FAILED';
export const RESET_VEHICLE_O_LOGIN = 'RESET_VEHICLE_O_LOGIN';

export const ATTEMPT_DELETE_VEHICLE = 'ATTEMPT_DELETE_VEHICLE';
export const DELETE_VEHICLE_SUCCESS = 'DELETE_VEHICLE_SUCCESS';
export const DELETE_VEHICLE_FAILED = 'DELETE_VEHICLE_FAILED';
export const RESET_DELETE_VEHICLE = 'RESET_DELETE_VEHICLE';

export const UPDATE_DRIVER_CREATE_PROPS = 'UPDATE_DRIVER_CREATE_PROPS';
export const ATTEMPT_DRIVER_CREATE = 'ATTEMPT_DRIVER_CREATE';
export const DRIVER_CREATE_SUCCESS = 'DRIVER_CREATE_SUCCESS';
export const DRIVER_CREATE_FAILED = 'DRIVER_CREATE_FAILED';
export const RESET_DRIVER_CREATE = 'RESET_DRIVER_CREATE';

export const UPDATE_UPDATE_PACKAGE_PROPS = 'UPDATE_UPDATE_PACKAGE_PROPS';
export const ATTEMPT_UPDATE_PACKAGE = 'ATTEMPT_UPDATE_PACKAGE';
export const UPDATE_PACKAGE_SUCCESS = 'UPDATE_PACKAGE_SUCCESS';
export const UPDATE_PACKAGE_FAILED = 'UPDATE_PACKAGE_FAILED';
export const RESET_UPDATE_PACKAGE = 'RESET_UPDATE_PACKAGE';

export const UPDATE_DRIVER_LIST_PROPS = 'UPDATE_DRIVER_LIST_PROPS';
export const ATTEMPT_DRIVER_LIST = 'ATTEMPT_DRIVER_LIST';
export const DRIVER_LIST_SUCCESS = 'DRIVER_LIST_SUCCESS';
export const DRIVER_LIST_FAILED = 'DRIVER_LIST_FAILED';
export const RESET_DRIVER_LIST = 'RESET_DRIVER_LIST';

export const UPDATE_DRIVER_DELETE_PROPS = 'UPDATE_DRIVER_DELETE_PROPS';
export const ATTEMPT_DRIVER_DELETE = 'ATTEMPT_DRIVER_DELETE';
export const DRIVER_DELETE_SUCCESS = 'DRIVER_DELETE_SUCCESS';
export const DRIVER_DELETE_FAILED = 'DRIVER_DELETE_FAILED';
export const RESET_DRIVER_DELETE = 'RESET_DRIVER_DELETE';

export const UPDATE_PACKAGE_CREATE_PROPS = 'UPDATE_PACKAGE_CREATE_PROPS';
export const ATTEMPT_PACKAGE_CREATE = 'ATTEMPT_PACKAGE_CREATE';
export const PACKAGE_CREATE_SUCCESS = 'PACKAGE_CREATE_SUCCESS';
export const PACKAGE_CREATE_FAILED = 'PACKAGE_CREATE_FAILED';
export const RESET_PACKAGE_CREATE = 'RESET_PACKAGE_CREATE';
